Comment allure
UA1252TAQC/greencity_py_pw pull request #28
Opened 2024-10-08 23:52 UTC by drozdovskyy

2024-10-09 16:41 UTC, FOleks approved these changes

2024-10-09 18:39 UTC, smelovd requested changes

2024-10-09 18:39 UTC, smelovd commented on .gitignore
> +allure-results/
remove, already exist in file

2024-10-09 18:39 UTC, smelovd commented on tests/api_tests/conftest.py
> +@allure.step("Get Authorisation Token")
Authorisation -> Authorization

2024-10-09 19:33 UTC, drozdovskyy commented on .gitignore
> +allure-results/
Done

2024-10-09 19:33 UTC, drozdovskyy commented on tests/api_tests/conftest.py
> +@allure.step("Get Authorisation Token")
Done

2024-10-10 08:49 UTC, ol271176 approved these changes

2024-10-10 09:51 UTC, smelovd approved these changes

2024-10-10 09:51 UTC, merged