Test  habit controller
UA1252TAQC/greencity_py_pw pull request #4
Opened 2024-10-03 22:49 UTC by OksanaFilipchuk

2024-10-04 13:25 UTC, Oyne commented on tests/api_tests/test_habit.py
refactor code with flake8 recomendations

2024-10-04 13:26 UTC, Oyne requested changes
refactor code with flake8 recomendations

2024-10-05 21:33 UTC, OksanaFilipchuk commented on tests/api_tests/test_habit.py
Fixed

2024-10-06 17:14 UTC, Oyne approved these changes

2024-10-06 23:24 UTC, drozdovskyy approved these changes

2024-10-06 23:25 UTC, merged