Addet test for post Subscription
UA1252TAQC/greencity_py_pw pull request #5
Opened 2024-10-04 07:54 UTC by sbekberov

2024-10-04 08:12 UTC, Oyne approved these changes

2024-10-04 13:26 UTC, Oyne approved these changes

2024-10-04 14:48 UTC, smelovd requested changes

2024-10-04 14:48 UTC, smelovd commented on tests/api_tests/subscription-controller/test_01.py
> +        print("Access forbidden: Check user permissions and token validity.")
remove statement

2024-10-04 14:48 UTC, smelovd commented on tests/api_tests/subscription-controller/test_01.py
> +def sign_in():
rename to get_auth_token(), or something like this

2024-10-07 07:22 UTC, rchuplak commented
In general LGTM

2024-10-07 18:36 UTC, smelovd approved these changes

2024-10-07 18:36 UTC, merged